### ISSUE TITLE
Switch to Java 11

### ISSUE THREAD

**Issue by ennioVisco** [MoonLightSuite/MoonLight#10]
Due to Java 8 end of life planned by the end of 2020, it's a good idea to switch to Java 11, which is the current LTS version of Java, and will be until 2021 at least.
Moreover, it adds some useful features - it's been 6 years since Java 8 :) (like modularization, new GC, local variables, etc. - [a non-exhaustive list of changes](https://codete.com/blog/java-8-java-11-quick-guide/)).

_Note that it might be particularly useful in light of #9._

In terms of repository changes, local tests show that it's trivial (two lines of code to change in the gradle settings). 
However, **developers working on Moonlight would have to install the** [appropriate jdk](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html) and properly set it up ([a guide for intelliJ](https://mkyong.com/intellij/how-to-change-the-intellij-idea-jdk-version/)).

**Comment by michele-loreti** [comment]
We moved to Java 11.
