### ISSUE TITLE
Common error

### ISSUE THREAD

**Issue by saramohammadinejad** [MoonLightSuite/MoonLight#19]
Hi,
I usually receive the following error while using Moonlight for monitoring. Any idea why I get this error?

Error using SpatialTemporalScriptComponent/monitor (line 47)
Java exception occurred:
java.lang.NullPointerException
	at
        eu.quanticol.moonlight.signal.Signal.arrayOf(Signal.java:398)
        	at
        eu.quanticol.moonlight.signal.SpatialTemporalSignal.lambda$toArray$7(SpatialTemporalSignal.java:137)
        	at
        java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        	at
        java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        	at
        eu.quanticol.moonlight.signal.SpatialTemporalSignal.toArray(SpatialTemporalSignal.java:137)
        	at
        eu.quanticol.moonlight.SpatialTemporalScriptComponent.monitorToObjectArrayAdjacencyList(SpatialTemporalScriptComponent.java:158)

Error in paramLearning (line 28)
resultReachMonitor =
Phi_Monitor.monitor(SpTemModel,time,values,[1,700,10]);

**Comment by michele-loreti** [comment]
Please, can you post the script you are using or, in case, the java snippet? It looks like you are trying to use a monitor that is not defined. Thanks.

**Comment by saramohammadinejad** [comment]
Thanks, Michele for your quick response!
Here is my Matlab code:

%% clear
clear all;
clc;

%% close all existing open plots, etc.
close all;

%% loading required matrices
load time
load values
load SpTemModel

clearvars -except time SpTemModel values

%% For reproducibility
rng(0,'twister'); 

%% get the path of current running file
[filepath,~,~] = fileparts(mfilename('fullpath'));
cd(filepath);

%% monitoring
moonlightScript = ScriptLoader.loadFromFile("bssMonitorScript");
moonlightScript.getMonitors();
Phi_Monitor = moonlightScript.getMonitor("Phi_3");
%moonlightScript.setBooleanDomain();
moonlightScript.setMinMaxDomain();
resultReachMonitor = Phi_Monitor.monitor(SpTemModel,time,values);

**Comment by michele-loreti** [comment]
Thank you, please can you post also the content of file "bssMonitorScript"? Have you checked that it this the exact file name? You could attach to your comment the file with the MoonLight script together with the content of "time", "values" and "SpTemModel". This will allow us to reproduce the error. Thanks.

**Comment by saramohammadinejad** [comment]
I sent you an email regarding this Michelle.

**Comment by michele-loreti** [comment]
Dear Sara, we have just committed a new version of MoonLight fixing this bug.
