### ISSUE TITLE
error for installation

### ISSUE THREAD

**Issue by saramohammadinejad** [MoonLightSuite/MoonLight#21]
I receive the following error after executing "./gradlew distribution" for installation. Any idea what the problem is?

> Configure project :console
exec distribution Task!

> Task :core:compileJava FAILED
/Users/saramohamadi/Desktop/jyo/Colab_Laura/MoonLight/core/src/main/java/eu/quanticol/moonlight/signal/StaticLocationService.java:23: error: cannot find symbol
        return List.of(new Pair<>(0.0,model)).iterator();
                   ^
  symbol:   method of(Pair<Double,SpatialModel<V>>)
  location: interface List
  where V is a type-variable:
    V extends Object declared in class StaticLocationService
Note: /Users/saramohamadi/Desktop/jyo/Colab_Laura/MoonLight/core/src/main/java/eu/quanticol/moonlight/util/ObjectSerializer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by ennioVisco** [comment]
Yes, there is a known problem with that method. Simply use JDK 9.0 instead of 8 and the problem should be solved

**Comment by ennioVisco** [comment]
@saramohammadinejad should be fixed in a1f5a0c007528198fef3eac175603a133a8b94c0. You might still want to use JDK8 in case you are using Moonlight with Matlab, which is the officially supported version by Matlab.
